name: nextjsapp CI pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Checkout repository
      - name: checkout code
        uses: actions/checkout@v3

      #set up docker buildx
      - name: set up docker
        uses: docker/setup-buildx-action@v2
      
      # needed to tag image
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      #build docker image for nextjs
      - name: build docker image for nextjsapp
        run: |
          docker compose -f docker-compose.yml build nextjs
       
      #build docker image for api
      - name: build docker image for api
        run: |
          docker compose -f docker-compose.yml build next-api
        env: 
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        
      #push image to AWS ECR
      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      #push image
      - name: push image to ECR
        run: |
          docker tag nextjs:latest 885554903941.dkr.ecr.us-east-1.amazonaws.com/nextjsapp:${IMAGE_TAG}
          docker tag next-api:latest 885554903941.dkr.ecr.us-east-1.amazonaws.com/nextapi:${IMAGE_TAG}
          docker push 885554903941.dkr.ecr.us-east-1.amazonaws.com/nextjsapp:${IMAGE_TAG}
          docker push 885554903941.dkr.ecr.us-east-1.amazonaws.com/nextapi:${IMAGE_TAG}
